apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-
  namespace: workflows
  annotations:
    workflows.argoproj.io/description: >-
      Demonstrates the HTTP template that executes a HTTP request.
      We run three http templates but you'll notice only one pod is created.
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://github.com/pipekit/talk-demos/argocon-demos/2025-argo-workflow-templates-a-practical-deep-dive'
    workflows.argoproj.io/version: '>= 3.6.0'
spec:
  serviceAccountName: workflows
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: get-example-homepage
            template: http
          - name: get-example-homepage-two
            template: http
            depends: get-example-homepage
          - name: get-example-homepage-three
            template: http
            depends: get-example-homepage
    - name: http
      http:
        url: https://example.com/
        method: "GET" # Default GET
        # Template will succeed if evaluated to true, otherwise will fail
        # Available variables:
        #  request.body: string, the request body
        #  request.headers: map[string][]string, the request headers
        #  response.url: string, the request url
        #  response.method: string, the request method
        #  response.statusCode: int, the response status code
        #  response.body: string, the response body
        #  response.headers: map[string][]string, the response headers
        # successCondition: "response.body contains \"google\"" # available since v3.3
        #body: "test body" # Change request body
    - name: container
      container:
        image: alpine
        command: [sh, -c]
        args: ["echo hello world && sleep 1"]
