apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-
  namespace: workflows
  annotations:
    workflows.argoproj.io/description: >-
      Demonstrates the HTTP template that executes a HTTP request.
      Note that due to https://github.com/argoproj/argo-workflows/issues/14211, you will need to remove the executor plugin configmap from your cluster before running this.
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://github.com/pipekit/talk-demos/argocon-demos/2025-argo-workflow-templates-a-practical-deep-dive'
    workflows.argoproj.io/version: '>= 3.6.0'
spec:
  serviceAccountName: workflows
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: get-example-homepage
            template: http
    - name: http
      http:
        timeoutSeconds: 20 # Default 30
        url: https://example.com/
        method: "GET" # Default GET
        # Template will succeed if evaluated to true, otherwise will fail
        # Available variables:
        #  request.body: string, the request body
        #  request.headers: map[string][]string, the request headers
        #  response.url: string, the request url
        #  response.method: string, the request method
        #  response.statusCode: int, the response status code
        #  response.body: string, the response body
        #  response.headers: map[string][]string, the response headers
        # successCondition: "response.body contains \"google\"" # available since v3.3
        #body: "test body" # Change request body
