apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: plugin-
  namespace: workflows
  annotations:
    workflows.argoproj.io/description: >-
      Runs an executor plugin using a Plugin template.
      The plugin was already installed to the cluster by `setup.sh`
      https://github.com/argoproj-labs/argo-workflows-hello-executor-plugin
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://github.com/pipekit/talk-demos/argocon-demos/2025-argo-workflow-templates-a-practical-deep-dive'
    workflows.argoproj.io/version: '>= 3.6.0'
spec:
  serviceAccountName: workflows
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }
