apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: suspend-
  namespace: workflows
  annotations:
    workflows.argoproj.io/description: >-
      Demonstrates the Suspend template that suspends the workflow.
      You can manually resume a suspended Workflow using the Argo CLI or the UI.
      `duration` is optional to automatically resume the Workflow after a certain duration.
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://github.com/pipekit/talk-demos/argocon-demos/2025-argo-workflow-templates-a-practical-deep-dive'
    workflows.argoproj.io/version: '>= 3.6.0'
spec:
  serviceAccountName: workflows
  entrypoint: suspend
  templates:
    - name: suspend
      suspend:
        duration: "20" # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h"
