---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "windy-city-config"
  namespace: "customer"
data:
  workflow: "1"
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: "windy-city"
  namespace: "customer"
spec:
  entrypoint: wrapped-workflow
  synchronization:
    semaphore:
      configMapKeyRef:
        name: "windy-city-config"
        key: workflow
  arguments:
    parameters:
      - name: n-workers
        value: "4"
      - name: worker-mcpu
        value: "300"
      - name: worker-mem-gb
        value: "0.3"
      - name: max-timestamps
        value: "1000"
  templates:
    - name: wrapped-workflow
      steps:
        - - name: dask-workflow
            templateRef:
              name: "dask-distributed-standard-workflow"
              template: main
              clusterScope: true
            arguments:
              parameters:
                # Set parameters for this particular pipeline
                - name: pipeline-dir
                  value: "/windy_city"
                - name: pipeline
                  value: "dask_pipeline.py"
                - name: image
                  value: "customer13/argocon21_dask:0.0.4"
                - name: scheduler-mcpu
                  value: "1000"
                - name: scheduler-mem-gb
                  value: "0.2"
                - name: pipeline-mcpu
                  value: "200"
                - name: pipeline-mem-gb
                  value: "0.2"
                # Inject configurable parameters
                - name: n-workers
                  value: "{{workflow.parameters.n-workers}}"
                - name: worker-mcpu
                  value: "{{workflow.parameters.worker-mcpu}}"
                - name: worker-mem-gb
                  value: "{{workflow.parameters.worker-mem-gb}}"
                - name: pipeline-arguments
                  value: "{{workflow.parameters.max-timestamps}}"

---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: windy-city
  namespace: customer
spec:
  schedule: "0 13 * * 1"
  timezone: "europe/berlin"
  successfulJobsHistoryLimit: 2
  workflowSpec:
    workflowTemplateRef:
      clusterScope: false
      name: "windy-city"
