apiVersion: v1
kind: Secret
metadata:
  name: workflow-python-secrets
type: Opaque
stringData:
  apiUser: <kaggle-api-user>
  apiPassword: <kaggle-api-password>
  awsAccessKeyId: <aws-access-key-id>
  awsSecretKey: <aws-secret-key>
