apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
type: Opaque
data:
  auth: dGVzdAo=
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    notify:
      port: "12000"
      endpoint: /notify
      method: POST
      filter:
        expression: "body.status == 'firing' && body.commonLabels.severity == 'critical' && body.commonLabels.alertname == 'CryptoMinerDetected'"
      authSecret:
        name: webhook-secret
        key: auth
