# This file describes the config settings available in the workflow controller configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:  
  executor: |
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Default values that will apply to all Workflows from this controller, unless overridden on the Workflow-level
  # See more: docs/default-workflow-specs.md
  workflowDefaults: |
    spec:
      # Time out after 1h
      activeDeadlineSeconds: 3600
      # Delete (archive) workflows after 48h
      ttlStrategy:
        secondsAfterCompletion: 172800
      volumeClaimGC:
        strategy: OnWorkflowCompletion
      retryStrategy:
        retryPolicy: OnError
        limit: 3
      serviceAccountName: argo

  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: workflows
      endpoint: minio.minio.svc.cluster.local:9000
      insecure: true
      accessKeySecret:
        name: minio-creds
        key: accesskey
      secretKeySecret:
        name: minio-creds
        key: secretkey
