---
apiVersion: v1
kind: Service
metadata:
  name: helmfile
  namespace: argocd
  labels:
    argocd.argoproj.io/plugin: "true"
spec:
  ports:
  - name: cmp
    port: 8080
    protocol: TCP
    targetPort: cmp
  selector:
    k8s-app: helmfile-aas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: helmfile-aas
  name: helmfile
  namespace: argocd
spec:
  selector:
    matchLabels:
      k8s-app: helmfile-aas
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: helmfile-aas
    spec:
      containers:
      - name: helmfile-aas
        command: ["/var/run/argocd/argocd-cmp-server"]
        image: joibel/argocd-plugin-helmfile-aas:latest
        ports:
        - containerPort: 8080
          name: cmp
          protocol: TCP
        volumeMounts:
          - name: auth-secret
            mountPath: /home/argocd/cmp-server/config/secret
            subPath: secret
      volumes:
        - name: auth-secret
          secret:
            secretName: paas
