apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-repo-server-svclist
rules:
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: repo-server-svclist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-repo-server-svclist
subjects:
- kind: ServiceAccount
  name: argocd-repo-server
  namespace: argocd
