apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-checkout
  annotations:
    workflows.argoproj.io/description: >-
      Clones a git repository and then performs a git checkout of a branch defined
      in the workflow.parameters.
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://pipekit.io'
    workflows.argoproj.io/version: '>= 3.4.0'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: git-checkout-pr
          template: git-checkout-pr

  - name: git-checkout
    container:
      image: alpine
      command:
        - sh
        - -c
        - |
          apk --update add git

          cd /workdir
          echo "Start Clone of source branch"
          git clone https://github.com/pipekit/{{workflow.parameters.app_repo}}.git
          cd {{workflow.parameters.app_repo}}

          git checkout {{workflow.parameters.git_branch}}

          echo "Complete."
      volumeMounts:
      - name: "workdir"
        mountPath: /workdir
      resources:
        requests:
          memory: 250Mi
          cpu: 4m
    #20 minutes
    activeDeadlineSeconds: 1200
