apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: run-unit-tests
  annotations:
    workflows.argoproj.io/description: >-
      Mocks the running of unit tests
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://pipekit.io'
    workflows.argoproj.io/version: '>= 3.4.0'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: run-unit-tests
          template: run-unit-tests

  - name: run-unit-tests
    container:
      image: alpine
      command:
        - sh
        - -c
        - |
          echo "Running unit tests... honest."
      volumeMounts:
      - name: "workdir"
        mountPath: /workdir
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
    #20 minutes
    activeDeadlineSeconds: 1200
