apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: scorecard-check
  annotations:
    workflows.argoproj.io/description: >-
      Mocks the running of the scorecard check
    workflows.argoproj.io/maintainer: 'Pipekit Inc'
    workflows.argoproj.io/maintainer_url: 'https://pipekit.io'
    workflows.argoproj.io/version: '>= 3.4.0'
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: scorecard-check
          template: scorecard-check

  - name: scorecard-check
    container:
      image: alpine
      command:
        - sh
        - -c
        - |
          echo "Running scorecard check... honest."
      volumeMounts:
      - name: "workdir"
        mountPath: /workdir
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
    #20 minutes
    activeDeadlineSeconds: 1200
